import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import { mkdtemp, mkdir, writeFile, readdir, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { workbenchApiPlugin } from "../server/vite-plugin-workbench.mjs";

test("knowledge routes require same origin and keep existing Vault writes blocked", async (t) => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), "knowledge-api-"));
  const root = path.join(tmp, "vault"); await mkdir(root);
  await writeFile(path.join(root, "note.md"), "# synthetic backup");
  const before = await readdir(root, { recursive: true });
  let middleware;
  const server = http.createServer((req, res) => middleware(req, res, () => { res.writeHead(404); res.end(); }));
  const plugin = workbenchApiPlugin({ vaultRoot: root, profile: "obsidian", readOnly: true, knowledgeOptions: { enabled: true, createEnabled: true, directory: path.join(tmp, "state"), modelConfig: { configured: true, model: "fixture", transportEncrypted: true }, model: { async complete({ onText }) { onText("资料 [S1]"); return { content: [{ type: "text", text: "资料 [S1]" }], stopReason: "end_turn" }; } } } });
  await plugin.configureServer({ httpServer: server, config: { logger: { error() {} } }, watcher: { add() {}, on() {}, off() {}, unwatch() {} }, middlewares: { use(handler) { middleware = handler; } } });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  t.after(async () => { await new Promise((resolve) => server.close(resolve)); await plugin.closeBundle(); await rm(tmp, { recursive: true, force: true }); });
  const origin = `http://127.0.0.1:${server.address().port}`;
  const post = (route, body, source = origin) => fetch(origin + route, { method: "POST", headers: { Origin: source, "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const status = await (await fetch(origin + "/api/knowledge-chat/status")).json();
  assert.equal(status.enabled, true);
  assert.equal(status.model, "fixture");
  assert.equal((await post("/api/knowledge-chat/sessions", {}, "https://evil.example")).status, 403);
  const response = await post("/api/knowledge-chat/sessions", {});
  assert.equal(response.status, 201);
  const session = await response.json();
  const stream = await post(`/api/knowledge-chat/sessions/${session.id}/messages`, { question: "backup" });
  assert.equal(stream.status, 200);
  const events = await stream.text();
  assert.match(events, /"type":"done"/);
  assert.equal((await post("/api/open", {})).status, 403);
  assert.equal((await post("/api/knowledge-chat/not-allowed", {})).status, 403);
  const saved = await (await fetch(origin + `/api/knowledge-chat/sessions/${session.id}`)).json();
  assert.equal(saved.messages.at(-1).status, "complete");
  assert.equal(JSON.stringify(saved).includes("confirmationToken"), false);
  assert.deepEqual(await readdir(root, { recursive: true }), before);
  const organized = await post(`/api/knowledge-chat/sessions/${session.id}/messages`, { question: "backup", mode: "organize" });
  assert.match(await organized.text(), /"type":"draft"/);
  const withDraft = await (await fetch(origin + `/api/knowledge-chat/sessions/${session.id}`)).json();
  const draft = withDraft.drafts.at(-1);
  const draftRoute = `/api/knowledge-chat/sessions/${session.id}/drafts/${draft.id}`;
  const preview = await (await post(draftRoute + "/preview", {})).json();
  assert.ok(preview.confirmationToken);
  assert.deepEqual(await readdir(root, { recursive: true }), before);
  const afterPreview = await (await fetch(origin + `/api/knowledge-chat/sessions/${session.id}`)).json();
  assert.equal(JSON.stringify(afterPreview).includes(preview.confirmationToken), false);
  assert.equal(JSON.stringify(afterPreview).includes("_confirmation"), false);
  const receiptResponse = await post(draftRoute + "/commit", { version: preview.version, confirmationToken: preview.confirmationToken });
  assert.equal(receiptResponse.status, 200);
  const receipt = await receiptResponse.json();
  assert.equal(receipt.path, "wiki/concepts/backup.md");
  assert.equal((await post("/api/open", {})).status, 403);
});
